# Generated by Django 4.1.5 on 2023-01-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название типа товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание типа товара')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название товара')),
                ('price', models.FloatField(default=0, verbose_name='Цена товара')),
                ('currency', models.CharField(choices=[('rub', 'Рубль'), ('usd', 'Доллар'), ('eur', 'Евро')], default='rub', max_length=6, verbose_name='Валюта')),
                ('in_stock', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Штрихкод')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка товара')),
                ('date_update', models.DateField(verbose_name='Обновлён')),
                ('manufacturer', models.CharField(max_length=70, verbose_name='Поставщик')),
                ('type_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type', to='market.type', verbose_name='Тип товара')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя клиента')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес клиента')),
                ('cart', models.ManyToManyField(to='market.product')),
            ],
        ),
    ]
